package com.daphne.es.crm.activities.entity;
// Generated 2015-10-10 17:21:35 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.daphne.es.common.entity.AbstractEntity;

/**
 * crm.Bcounterselection generated by hbm2java
 */
@Entity
@Table(name = "BCOUNTERSELECTION", schema = "CRM")
public class Bcounterselection extends AbstractEntity<BigDecimal> {

	private BigDecimal ctsId;
	private String ctsName;
	private String ctsDesc;
	private String ctsSql;
	private String ctsOrderNum;
	private String ctsCode;
	private String ctsCreationuid;
	private Date ctsUpdateDt;
	private Date ctsCreationDt;
	private String ctsUpdateuid;

	public Bcounterselection() {
	}

	public Bcounterselection(BigDecimal ctsId) {
		this.ctsId = ctsId;
	}

	public Bcounterselection(BigDecimal ctsId, String ctsName, String ctsDesc, String ctsSql, String ctsOrderNum,
			String ctsCode, String ctsCreationuid, Date ctsUpdateDt, Date ctsCreationDt, String ctsUpdateuid) {
		this.ctsId = ctsId;
		this.ctsName = ctsName;
		this.ctsDesc = ctsDesc;
		this.ctsSql = ctsSql;
		this.ctsOrderNum = ctsOrderNum;
		this.ctsCode = ctsCode;
		this.ctsCreationuid = ctsCreationuid;
		this.ctsUpdateDt = ctsUpdateDt;
		this.ctsCreationDt = ctsCreationDt;
		this.ctsUpdateuid = ctsUpdateuid;
	}

	@Column(name = "CTS_CODE", length = 100)
	public String getCtsCode() {
		return this.ctsCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CTS_CREATION_DT", length = 7)
	public Date getCtsCreationDt() {
		return this.ctsCreationDt;
	}

	@Column(name = "CTS_CREATIONUID", length = 50)
	public String getCtsCreationuid() {
		return this.ctsCreationuid;
	}

	@Column(name = "CTS_DESC", length = 100)
	public String getCtsDesc() {
		return this.ctsDesc;
	}

	@Column(name = "CTS_NAME", length = 100)
	public String getCtsName() {
		return this.ctsName;
	}

	@Column(name = "CTS_ORDER_NUM", length = 10)
	public String getCtsOrderNum() {
		return this.ctsOrderNum;
	}

	@Column(name = "CTS_SQL", length = 4000)
	public String getCtsSql() {
		return this.ctsSql;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CTS_UPDATE_DT", length = 7)
	public Date getCtsUpdateDt() {
		return this.ctsUpdateDt;
	}

	@Column(name = "CTS_UPDATEUID", length = 50)
	public String getCtsUpdateuid() {
		return this.ctsUpdateuid;
	}

	@Override
	@Id
	@Column(name = "CTS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.ctsId;
	}

	public void setCtsCode(String ctsCode) {
		this.ctsCode = ctsCode;
	}

	public void setCtsCreationDt(Date ctsCreationDt) {
		this.ctsCreationDt = ctsCreationDt;
	}

	public void setCtsCreationuid(String ctsCreationuid) {
		this.ctsCreationuid = ctsCreationuid;
	}

	public void setCtsDesc(String ctsDesc) {
		this.ctsDesc = ctsDesc;
	}

	public void setCtsName(String ctsName) {
		this.ctsName = ctsName;
	}

	public void setCtsOrderNum(String ctsOrderNum) {
		this.ctsOrderNum = ctsOrderNum;
	}

	public void setCtsSql(String ctsSql) {
		this.ctsSql = ctsSql;
	}

	public void setCtsUpdateDt(Date ctsUpdateDt) {
		this.ctsUpdateDt = ctsUpdateDt;
	}

	public void setCtsUpdateuid(String ctsUpdateuid) {
		this.ctsUpdateuid = ctsUpdateuid;
	}

	@Override
	public void setId(BigDecimal ctsId) {
		this.ctsId = ctsId;
	}

}
