package com.daphne.es.crm.activities.entity;
// Generated 2015-9-15 17:04:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.daphne.es.common.entity.AbstractEntity;

/**
 * CrmActivityCouponRule generated by hbm2java
 */
@Entity
@Table(name = "CRM_ACTIVITY_COUPON_RULE", schema = "MAS")
public class CrmActivityCouponRule extends AbstractEntity<BigDecimal> {

	private BigDecimal caclId;
	private BigDecimal casId;
	private BigDecimal caId;
	private BigDecimal saleAmount;
	private BigDecimal discountAmount;
	private String brand;
	private CrmActivityCoupon crmActivityCoupon;

	public CrmActivityCouponRule() {
	}

	public CrmActivityCouponRule(BigDecimal caclId, BigDecimal casId, BigDecimal caId) {
		this.caclId = caclId;
		this.casId = casId;
		this.caId = caId;
	}

	public CrmActivityCouponRule(BigDecimal caclId, BigDecimal casId, BigDecimal caId, BigDecimal saleAmount,
			BigDecimal discountAmount, String brand) {
		this.caclId = caclId;
		this.casId = casId;
		this.caId = caId;
		this.saleAmount = saleAmount;
		this.discountAmount = discountAmount;
		this.brand = brand;
	}

	public CrmActivityCouponRule(BigDecimal casId, BigDecimal caId, BigDecimal saleAmount, BigDecimal discountAmount,
			String brand) {
		super();
		this.casId = casId;
		this.caId = caId;
		this.saleAmount = saleAmount;
		this.discountAmount = discountAmount;
		this.brand = brand;
	}

	@Column(name = "BRAND", length = 10)
	public String getBrand() {
		return this.brand;
	}

	@Column(name = "CA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCaId() {
		return this.caId;
	}

	@Column(name = "CAS_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCasId() {
		return this.casId;
	}

	@ManyToOne(targetEntity = CrmActivityCoupon.class)
	@JoinColumn(name = "CAC_ID", referencedColumnName = "CAC_ID")
	public CrmActivityCoupon getCrmActivityCoupon() {
		return crmActivityCoupon;
	}

	@Column(name = "DISCOUNT_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@SequenceGenerator(name = "seq", sequenceName = "CRM_ACTIVITY_COUPON_RULE_S", allocationSize = 1)
	@Column(name = "CACL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@Override
	public BigDecimal getId() {
		return this.caclId;
	}

	@Column(name = "SALE_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getSaleAmount() {
		return this.saleAmount;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public void setCaId(BigDecimal caId) {
		this.caId = caId;
	}

	public void setCasId(BigDecimal casId) {
		this.casId = casId;
	}

	public void setCrmActivityCoupon(CrmActivityCoupon crmActivityCoupon) {
		this.crmActivityCoupon = crmActivityCoupon;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Override
	public void setId(BigDecimal caclId) {
		this.caclId = caclId;
	}

	public void setSaleAmount(BigDecimal saleAmount) {
		this.saleAmount = saleAmount;
	}

}
