package com.daphne.es.crm.activities.entity;
// Generated 2015-9-15 17:04:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.springframework.format.annotation.DateTimeFormat;

import com.daphne.es.common.entity.AbstractEntity;

import com.google.common.collect.Lists;
import com.daphne.es.common.plugin.entity.TransientTreeable;
import com.daphne.es.common.plugin.entity.Treeable;

/**
 * CrmActivityCoupon generated by hbm2java
 */
@Entity
@Table(name = "CRM_ACTIVITY_COUPON", schema = "MAS")
public class CrmActivityCoupon extends TransientTreeable<BigDecimal> implements Treeable<BigDecimal> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal cacId;
//	private BigDecimal casId;
//	private BigDecimal caId;
	private Date startDate;
	private Date endDate;
	private String title;
	private String brand;
	private BigDecimal amount;
	private BigDecimal quantiy;
	private String sendMsg;
	private Date createDate;
	private String createDt;
	private Date updateDate;
	private String updateDt;

	private List<CrmActivityCouponRule> crmActivityCouponRule;

	private CrmActivity CrmActivity;
	
	private CrmActivitySteps crmActivitySteps;
	
	public CrmActivityCoupon() {

	}
	
	public CrmActivityCoupon(BigDecimal cacId, Date startDate, Date endDate,
			String title, String brand, BigDecimal amount, BigDecimal quantiy, String sendMsg, Date createDate,
			String createDt, Date updateDate, String updateDt) {

		this.cacId = cacId;
//		this.casId = casId;
//		this.caId = caId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.title = title;
		this.brand = brand;
		this.amount = amount;
		this.quantiy = quantiy;
		this.sendMsg = sendMsg;
		this.createDate = createDate;
		this.createDt = createDt;
		this.updateDate = updateDate;
		this.updateDt = updateDt;

	}
	public void addCouponRule(CrmActivityCouponRule crmActivityCouponRule) {
		crmActivityCouponRule.setCrmActivityCoupon(this);
		getCrmActivityCouponRule().add(crmActivityCouponRule);
	}

	@Column(name = "AMOUNT", precision = 22, scale = 0)
	public BigDecimal getAmount() {
		return this.amount;
	}

	@Column(name = "BRAND", length = 10)
	public String getBrand() {
		return this.brand;
	}

//	public CrmActivityCoupon(BigDecimal casId, BigDecimal caId) {
//		this.casId = casId;
//		this.caId = caId;
//	}
//
//	public CrmActivityCoupon(BigDecimal cacId, BigDecimal casId, BigDecimal caId) {
//
//		this.cacId = cacId;
//		this.casId = casId;
//		this.caId = caId;
//	}

	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	@Column(name = "CREATE_DT", length = 30)
	public String getCreateDt() {
		return this.createDt;
	}

	@ManyToOne(targetEntity = CrmActivity.class)
	@JoinColumn(name = "CA_ID", referencedColumnName = "CA_ID")
	public CrmActivity getCrmActivity() {
		return CrmActivity;
	}

	
	@OneToMany(mappedBy = "crmActivityCoupon", cascade = CascadeType.ALL, fetch = FetchType.EAGER, targetEntity = CrmActivityCouponRule.class)
	@Fetch(FetchMode.SELECT)
	public List<CrmActivityCouponRule> getCrmActivityCouponRule() {

		if (crmActivityCouponRule == null) {
			crmActivityCouponRule = Lists.newArrayList();
		}
		return crmActivityCouponRule;
	}

//	@Column(name = "CA_ID", nullable = false, precision = 22, scale = 0)
//	public BigDecimal getCaId() {
//		return this.caId;
//	}
//
//	@Column(name = "CAS_ID", nullable = false, precision = 22, scale = 0)
//	public BigDecimal getCasId() {
//		return this.casId;
//	}

	@ManyToOne(targetEntity = CrmActivitySteps.class)
	@JoinColumn(name = "CAS_ID", referencedColumnName = "CAS_ID")
	public CrmActivitySteps getCrmActivitySteps() {
		return crmActivitySteps;
	}

	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@SequenceGenerator(name = "seq", sequenceName = "CRM_ACTIVITY_COUPON_S", allocationSize = 1)
	@Column(name = "CAC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@Override
	public BigDecimal getId() {
		return this.cacId;
	}

	
	@Transient
	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return getTitle();
	}


	@Column(name = "QUANTIY", precision = 22, scale = 0)
	public BigDecimal getQuantiy() {
		return this.quantiy;
	}

	


	@Column(name = "SEND_MSG", length = 1000)
	public String getSendMsg() {
		return this.sendMsg;
	}

	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}


	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}

	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	

	@Column(name = "UPDATE_DT", length = 30)
	public String getUpdateDt() {
		return this.updateDt;
	}





	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

//	public void setCaId(BigDecimal caId) {
//		this.caId = caId;
//	}
//
//	public void setCasId(BigDecimal casId) {
//		this.casId = casId;
//	}

	public void setCreateDt(String createDt) {
		this.createDt = createDt;
	}

	
	

	public void setCrmActivity(CrmActivity crmActivity) {
		CrmActivity = crmActivity;
	}

	public void setCrmActivityCouponRule(List<CrmActivityCouponRule> crmActivityCouponRule) {
		this.crmActivityCouponRule = crmActivityCouponRule;
	}

	
	
	public void setCrmActivitySteps(CrmActivitySteps crmActivitySteps) {
		this.crmActivitySteps = crmActivitySteps;
	}




	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	

	@Override
	public void setId(BigDecimal cacId) {
		this.cacId = cacId;
	}

	public void setQuantiy(BigDecimal quantiy) {
		this.quantiy = quantiy;
	}

	

	public void setSendMsg(String sendMsg) {
		this.sendMsg = sendMsg;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public void setUpdateDt(String updateDt) {
		this.updateDt = updateDt;
	}
	@Transient
	@Override
	public String getDiy() {
		// TODO Auto-generated method stub
		return getId()+"";
	}
}
