package com.daphne.es.crm.activities.entity;
// Generated 2015-9-15 17:04:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.daphne.es.common.entity.AbstractEntity;

/**
 * CrmActivitySendType generated by hbm2java
 */
@Entity
@Table(name = "CRM_ACTIVITY_SEND_TYPE", schema = "MAS")
public class CrmActivitySendType extends AbstractEntity<BigDecimal> {

	private BigDecimal castId;
	private BigDecimal casId;
	private BigDecimal caId;
	private BigDecimal sendType;
	private Date sendTime;

	public CrmActivitySendType() {
	}

	public CrmActivitySendType(BigDecimal castId, BigDecimal casId, BigDecimal caId, BigDecimal sendType,
			Date sendTime) {
		this.castId = castId;
		this.casId = casId;
		this.caId = caId;
		this.sendType = sendType;
		this.sendTime = sendTime;
	}

	@Column(name = "CA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCaId() {
		return this.caId;
	}

	@Column(name = "CAS_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCasId() {
		return this.casId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@SequenceGenerator(name = "seq", sequenceName = "CRM_ACTIVITY_SEND_TYPE_S", allocationSize = 1)
	@Column(name = "CAST_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@Override
	public BigDecimal getId() {
		return this.castId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SEND_TIME", nullable = false, length = 7)
	public Date getSendTime() {
		return this.sendTime;
	}

	@Column(name = "SEND_TYPE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSendType() {
		return this.sendType;
	}

	public void setCaId(BigDecimal caId) {
		this.caId = caId;
	}

	public void setCasId(BigDecimal casId) {
		this.casId = casId;
	}

	@Override
	public void setId(BigDecimal castId) {
		this.castId = castId;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public void setSendType(BigDecimal sendType) {
		this.sendType = sendType;
	}

}
