package com.daphne.es.crm.activities.entity;
// Generated 2015-9-15 17:04:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

import com.daphne.es.common.plugin.entity.TransientTreeable;
import com.daphne.es.common.plugin.entity.Treeable;

/**
 * CrmActivityPromotion generated by hbm2java
 */
@Entity
@Table(name = "CRM_ACTIVITY_PROMOTION", schema = "MAS")
public class CrmActivityPromotion extends TransientTreeable<BigDecimal> implements Treeable<BigDecimal> {

	public CrmActivityPromotion(CrmActivity crmActivity) {
		super();
		this.crmActivity = crmActivity;
	}


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal capId;
	// private BigDecimal casId;
	// private BigDecimal caId;
	private String title;
	private Date startDate;
	private Date endDate;
	private String brand;
	private String vipType;
	private BigDecimal promotionType;
	private BigDecimal amount;
	private BigDecimal discount;
	private BigDecimal offOrOnLine;
	private String sendMsg;
	private Date createDate;
	private String createDt;
	private Date updateDate;
	private String updateDt;

	private CrmActivitySteps crmActivitySteps;

	private CrmActivity crmActivity;

	

	public CrmActivityPromotion() {
	}

	public CrmActivityPromotion(BigDecimal capId) {
		this.capId = capId;
	}

	public CrmActivityPromotion(BigDecimal capId, String title, Date startDate, Date endDate, String brand,
			String vipType, BigDecimal promotionType, BigDecimal amount, BigDecimal discount, BigDecimal offOrOnLine,
			String sendMsg, Date createDate, String createDt, Date updateDate, String updateDt) {
		this.capId = capId;
		// this.casId = casId;
		// this.caId = caId;
		this.title = title;
		this.startDate = startDate;
		this.endDate = endDate;
		this.brand = brand;
		this.vipType = vipType;
		this.promotionType = promotionType;
		this.amount = amount;
		this.discount = discount;
		this.offOrOnLine = offOrOnLine;
		this.sendMsg = sendMsg;
		this.createDate = createDate;
		this.createDt = createDt;
		this.updateDate = updateDate;
		this.updateDt = updateDt;
	}

	@Column(name = "AMOUNT", precision = 22, scale = 0)
	public BigDecimal getAmount() {
		return this.amount;
	}

	/**
	 * 树枝节点默认图标 如果没有默认 空即可
	 *
	 * @return
	 */
	@Transient
	@Override
	public String getBranchDefaultIcon() {
		return "ztree_folder";
	}

	@Column(name = "BRAND", length = 10)
	public String getBrand() {
		return this.brand;
	}

	@DateTimeFormat(pattern="yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	@Column(name = "CREATE_DT", length = 30)
	public String getCreateDt() {
		return this.createDt;
	}

	@ManyToOne
	@JoinColumn(name = "CA_ID", insertable = true, updatable = true, referencedColumnName = "CA_ID")
	public CrmActivity getCrmActivity() {
		return crmActivity;
	}

	@ManyToOne
	@JoinColumn(name = "CAS_ID", insertable = true, updatable = true)
	public CrmActivitySteps getCrmActivitySteps() {
		return crmActivitySteps;
	}

	@Column(name = "DISCOUNT", precision = 22, scale = 0)
	public BigDecimal getDiscount() {
		return this.discount;
	}



	@DateTimeFormat(pattern="yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@SequenceGenerator(name = "seq", sequenceName = "CRM_ACTIVITY_PROMOTION_S", allocationSize = 1)
	@Column(name = "CAP_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@Override
	public BigDecimal getId() {
		return this.capId;
	}


	@Column(name = "OFF_OR_ON_LINE", precision = 22, scale = 0)
	public BigDecimal getOffOrOnLine() {
		return this.offOrOnLine;
	}

	
	@Column(name = "PROMOTION_TYPE", precision = 22, scale = 0)
	public BigDecimal getPromotionType() {
		return this.promotionType;
	}

	/**
	 * 根节点默认图标 如果没有默认 空即可
	 *
	 * @return
	 */


	@Column(name = "SEND_MSG", length = 1000)
	public String getSendMsg() {
		return this.sendMsg;
	}


	@DateTimeFormat(pattern="yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}

	
	@DateTimeFormat(pattern="yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	@Column(name = "UPDATE_DT", length = 30)
	public String getUpdateDt() {
		return this.updateDt;
	}



	@Column(name = "VIP_TYPE", length = 10)
	public String getVipType() {
		return this.vipType;
	}

	


	

	@Override
	public String makeSelfAsNewParentIds() {
		return getParentIds() + getId() + getSeparator();
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public void setCreateDt(String createDt) {
		this.createDt = createDt;
	}

	public void setCrmActivity(CrmActivity crmActivity) {
		this.crmActivity = crmActivity;
	}

	public void setCrmActivitySteps(CrmActivitySteps crmActivitySteps) {
		this.crmActivitySteps = crmActivitySteps;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	

	@Override
	public void setId(BigDecimal capId) {
		this.capId = capId;
	}

	
	public void setOffOrOnLine(BigDecimal offOrOnLine) {
		this.offOrOnLine = offOrOnLine;
	}


	public void setPromotionType(BigDecimal promotionType) {
		this.promotionType = promotionType;
	}

	public void setSendMsg(String sendMsg) {
		this.sendMsg = sendMsg;
	}


	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public void setUpdateDt(String updateDt) {
		this.updateDt = updateDt;
	}

	
	public void setVipType(String vipType) {
		this.vipType = vipType;
	}
	@Transient
	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return getTitle();
	}
	@Transient
	@Override
	public String getDiy() {
		// TODO Auto-generated method stub
		return getId()+"";
	}
}
