package com.daphne.es.crm.activities.entity;
// Generated 2015-9-15 17:04:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringUtils;
import com.daphne.es.common.entity.AbstractEntity;
import com.daphne.es.common.plugin.entity.Treeable;

/**
 * CrmActivityActivitys generated by hbm2java
 */
@Entity
@Table(name = "CRM_ACTIVITY_ACTIVITYS", schema = "MAS")
public class CrmActivityActivitys extends AbstractEntity<BigDecimal> implements Treeable<BigDecimal> {

	private BigDecimal caaId;

	private BigDecimal casId;

	private BigDecimal caId;

	private BigDecimal caamId;

	private String activityNo;

	private BigDecimal vip;

	private Date createDate;

	/**
	 * 标题
	 */
	private String name;

	/**
	 * 资源标识符 用于权限匹配的 如sys:resource
	 */
	private String identity = "";

	/**
	 * 点击后前往的地址 菜单才有
	 */
	private String url;

	/**
	 * 父路径
	 */

	private BigDecimal parentId;

	private String parentIds;

	private Integer weight;

	/**
	 * 图标
	 */
	private String icon;

	/**
	 * 是否有叶子节点
	 */
	// @Formula(value = "(select count(*) from sys_resource f_t where
	// f_t.parent_id = id)")
	private boolean hasChildren;

	/**
	 * 是否显示
	 */

	private Boolean show = Boolean.FALSE;

	private String diy;

	public CrmActivityActivitys() {
	}

	public CrmActivityActivitys(BigDecimal caaId, BigDecimal casId, BigDecimal caId, BigDecimal caamId) {
		this.caaId = caaId;
		this.casId = casId;
		this.caId = caId;
		this.caamId = caamId;
	}

	public CrmActivityActivitys(BigDecimal caaId, BigDecimal casId, BigDecimal caId, BigDecimal caamId,
			String activityNo, BigDecimal vip, Date createDate) {
		this.caaId = caaId;
		this.casId = casId;
		this.caId = caId;
		this.caamId = caamId;
		this.activityNo = activityNo;
		this.vip = vip;
		this.createDate = createDate;
	}

	@Column(name = "ACTIVITY_NO", length = 30)
	public String getActivityNo() {
		return this.activityNo;
	}

	/**
	 * 树枝节点默认图标 如果没有默认 空即可
	 *
	 * @return
	 */
	@Transient
	@Override
	public String getBranchDefaultIcon() {
		return "ztree_folder";
	}

	@Column(name = "CAAM_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCaamId() {
		return this.caamId;
	}

	@Column(name = "CA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCaId() {
		return this.caId;
	}

	@Column(name = "CAS_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCasId() {
		return this.casId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	@Override
	@Transient
	public String getDiy() {
		return diy;
	}

	@Override
	@Transient
	public String getIcon() {
		if (!StringUtils.isEmpty(icon)) {
			return icon;
		}
		if (isRoot()) {
			return getRootDefaultIcon();
		}
		if (isLeaf()) {
			return getLeafDefaultIcon();
		}
		return getBranchDefaultIcon();
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@SequenceGenerator(name = "seq", sequenceName = "CRM_ACTIVITY_ACTIVITYS_S", allocationSize = 1)
	@Column(name = "CAA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@Override
	public BigDecimal getId() {
		return this.caaId;
	}

	@Transient
	public String getIdentity() {
		return identity;
	}

	/**
	 * 树叶节点默认图标 如果没有默认 空即可
	 *
	 * @return
	 */
	@Transient
	@Override
	public String getLeafDefaultIcon() {
		return "ztree_file";
	}

	@Override
	@Transient
	public String getName() {

		return name;
	}

	@Override
	@Transient
	@Column(name = "parent_id")
	public BigDecimal getParentId() {
		return parentId;
	}

	@Override
	@Transient
	@Column(name = "parent_ids")
	public String getParentIds() {
		return parentIds;
	}

	/**
	 * 根节点默认图标 如果没有默认 空即可
	 *
	 * @return
	 */
	@Transient
	@Override
	public String getRootDefaultIcon() {
		return "ztree_setting";
	}

	@Transient
	@Override
	public String getSeparator() {
		return "/";
	}

	@Transient
	@Column(name = "is_show")
	public Boolean getShow() {
		return show;
	}

	@Transient
	public String getTreetableIds() {
		String selfId = makeSelfAsNewParentIds().replace("/", "-");
		return selfId.substring(0, selfId.length() - 1);
	}

	@Transient
	public String getTreetableParentIds() {
		String parentIds = getParentIds().replace("/", "-");
		return parentIds.substring(0, parentIds.length() - 1);
	}

	@Transient
	public String getUrl() {
		return url;
	}

	@Column(name = "VIP", precision = 22, scale = 0)
	public BigDecimal getVip() {
		return this.vip;
	}

	@Override
	@Transient
	public Integer getWeight() {
		return weight;
	}

	@Override
	@Transient
	public boolean isHasChildren() {
		return hasChildren;
	}

	@Transient
	@Override
	public boolean isLeaf() {
		if (isRoot()) {
			return false;
		}
		if (isHasChildren()) {
			return false;
		}

		return true;
	}

	@Transient
	@Override
	public boolean isRoot() {
		if (getParentId() != null && getParentId().longValue() == 0) {
			return true;
		}
		return false;
	}

	@Override
	public String makeSelfAsNewParentIds() {
		return getParentIds() + getId() + getSeparator();
	}

	public void setActivityNo(String activityNo) {
		this.activityNo = activityNo;
	}

	public void setCaamId(BigDecimal caamId) {
		this.caamId = caamId;
	}

	public void setCaId(BigDecimal caId) {
		this.caId = caId;
	}

	public void setCasId(BigDecimal casId) {
		this.casId = casId;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Override
	public void setDiy(String diy) {
		this.diy = diy;
	}

	public void setHasChildren(boolean hasChildren) {
		this.hasChildren = hasChildren;
	}

	@Override
	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Override
	public void setId(BigDecimal caaId) {
		this.caaId = caaId;
	}

	public void setIdentity(String identity) {
		this.identity = identity;
	}

	@Override
	public void setName(String name) {
		this.name = name;
	}

	@Override
	public void setParentId(BigDecimal parentId) {
		this.parentId = parentId;
	}

	@Override
	public void setParentIds(String parentIds) {
		this.parentIds = parentIds;
	}

	public void setShow(Boolean show) {
		this.show = show;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public void setVip(BigDecimal vip) {
		this.vip = vip;
	}

	@Override
	public void setWeight(Integer weight) {
		this.weight = weight;
	}

}
