package com.daphne.es.crm.activities.entity;
// Generated 2015-9-15 17:04:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

import com.daphne.es.common.plugin.entity.TransientTreeable;
import com.daphne.es.common.plugin.entity.Treeable;

/**
 * CrmActivityAd generated by hbm2java
 */
@Entity
@Table(name = "CRM_ACTIVITY_AD", schema = "MAS")
public class CrmActivityAd extends TransientTreeable<BigDecimal> implements Treeable<BigDecimal> {

	private BigDecimal caadId;
	//private BigDecimal casId;
	// private BigDecimal caId;
	private String title;
	private Date startDate;
	private Date endDate;
	private String brand;
	private String sendMsg;
	private Date createDate;
	private String createDt;
	private Date updateDate;
	private String updateDt;

	private CrmActivitySteps crmActivitySteps;

	private CrmActivity crmActivity;

	public CrmActivityAd() {
	}
	
	
	public CrmActivityAd(BigDecimal caadId) {
		this.caadId = caadId;
	}
	
	public CrmActivityAd(CrmActivity crmActivity) {
		this.crmActivity = crmActivity;
	}

	public CrmActivityAd(BigDecimal caadId, String title, Date startDate, Date endDate, String brand, String sendMsg,
			Date createDate, String createDt, Date updateDate, String updateDt) {
		this.caadId = caadId;
		this.title = title;
		this.startDate = startDate;
		this.endDate = endDate;
		this.brand = brand;
		this.sendMsg = sendMsg;
		this.createDate = createDate;
		this.createDt = createDt;
		this.updateDate = updateDate;
		this.updateDt = updateDt;
	}



	@Column(name = "BRAND", length = 10)
	public String getBrand() {
		return this.brand;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	@Column(name = "CREATE_DT", length = 30)
	public String getCreateDt() {
		return this.createDt;
	}

	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "CA_ID", insertable = true, updatable = true)
	public CrmActivity getCrmActivity() {
		return crmActivity;
	}
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name = "CAS_ID", insertable = true, updatable = true)
	public CrmActivitySteps getCrmActivitySteps() {
		return crmActivitySteps;
	}


	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@SequenceGenerator(name = "seq", sequenceName = "CRM_ACTIVITY_AD_S", allocationSize = 1)
	@Column(name = "CAAD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@Override
	public BigDecimal getId() {
		return this.caadId;
	}

	

	@Column(name = "SEND_MSG", length = 1000)
	public String getSendMsg() {
		return this.sendMsg;
	}

	

	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}



	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	@Column(name = "UPDATE_DT", length = 30)
	public String getUpdateDt() {
		return this.updateDt;
	}

	

	@Override
	public String makeSelfAsNewParentIds() {
		return getParentIds() + getId() + getSeparator();
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public void setCreateDt(String createDt) {
		this.createDt = createDt;
	}

	public void setCrmActivity(CrmActivity crmActivity) {
		this.crmActivity = crmActivity;
	}

	public void setCrmActivitySteps(CrmActivitySteps crmActivitySteps) {
		this.crmActivitySteps = crmActivitySteps;
	}

	

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	
	public void setSendMsg(String sendMsg) {
		this.sendMsg = sendMsg;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	@Override
	public void setId(BigDecimal caadId) {
		this.caadId = caadId;
	}
	public void setUpdateDt(String updateDt) {
		this.updateDt = updateDt;
	}
	@Transient
	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return getTitle();
	}
	@Transient
	@Override
	public String getDiy() {
		// TODO Auto-generated method stub
		return getId()+"";
	}
}
