package com.daphne.es.crm.activities.entity;
// Generated 2015-9-15 17:04:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

import com.daphne.es.common.plugin.entity.TransientTreeable;
import com.daphne.es.common.plugin.entity.Treeable;
import com.google.common.collect.Lists;

/**
 * CrmActivity generated by hbm2java
 */
@Entity
@Table(name = "CRM_ACTIVITY", schema = "MAS")
public class CrmActivity extends TransientTreeable<BigDecimal> implements Treeable<BigDecimal> {

	private BigDecimal caId;
	private String title;
	private Date startDate;
	private Date endDate;
	private String brand;
	private BigDecimal status;
	private String remark;
	private Date createDate;
	private String createDt;
	private Date updateDate;
	private String updateDt;

	////////////////////////////////////////////////////////////////////////
	private List<CrmActivitySteps> crmActivitySteps = new ArrayList<CrmActivitySteps>();

	////////////////////////////////////////////////////////////////////////
	
	private List<CrmActivityAd> crmActivityAds = new ArrayList<CrmActivityAd>();
	private List<CrmActivityPromotion> crmActivityPromotions;
	
	private List<CrmActivityCoupon> crmActivityCoupons;

	// @Fetch(FetchMode.SELECT)
	// @Basic(optional = true, fetch = FetchType.EAGER)
	// @Cascade(value = org.hibernate.annotations.CascadeType.ALL)
	// @OrderBy()

	private List<CrmActivityHpoint> crmActivityHpoints;

	private List<CrmActivityActivitysManager> crmActivityActivitysManagers;

	

	public CrmActivity() {
	}

	public CrmActivity(BigDecimal caId) {
		this.caId = caId;
	}

	public CrmActivity(BigDecimal caId, String title, Date startDate, Date endDate, String brand, BigDecimal status,
			String remark, Date createDate, String createDt, Date updateDate, String updateDt) {
		this.caId = caId;
		this.title = title;
		this.startDate = startDate;
		this.endDate = endDate;
		this.brand = brand;
		this.status = status;
		this.remark = remark;
		this.createDate = createDate;
		this.createDt = createDt;
		this.updateDate = updateDate;
		this.updateDt = updateDt;
	}

	/**
	 * 树枝节点默认图标 如果没有默认 空即可
	 *
	 * @return
	 */
	@Transient
	@Override
	public String getBranchDefaultIcon() {
		return "ztree_folder";
	}

	@Column(name = "BRAND", length = 10)
	public String getBrand() {
		return this.brand;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	@Column(name = "CREATE_DT", length = 30)
	public String getCreateDt() {
		return this.createDt;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "crmActivity", fetch = FetchType.LAZY, targetEntity = CrmActivityActivitysManager.class)
	public List<CrmActivityActivitysManager> getCrmActivityActivitysManagers() {
		if (crmActivityActivitysManagers == null) {
			crmActivityActivitysManagers = Lists.newArrayList();
		}
		return crmActivityActivitysManagers;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, targetEntity = CrmActivityAd.class, mappedBy = "crmActivity", orphanRemoval = false)
	public List<CrmActivityAd> getCrmActivityAds() {
		if (crmActivityAds == null) {
			crmActivityAds = Lists.newArrayList();
		}
		return crmActivityAds;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "crmActivity", fetch = FetchType.LAZY, targetEntity = CrmActivityHpoint.class)
	public List<CrmActivityHpoint> getCrmActivityHpoints() {
		if (crmActivityHpoints == null) {
			crmActivityHpoints = Lists.newArrayList();
		}
		return crmActivityHpoints;
	}

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "crmActivity", fetch = FetchType.LAZY, targetEntity = CrmActivityPromotion.class)
	public List<CrmActivityPromotion> getCrmActivityPromotions() {
		if (crmActivityPromotions == null) {
			crmActivityPromotions = Lists.newArrayList();
		}
		return crmActivityPromotions;
	}
	

	
	@OneToMany(cascade = CascadeType.ALL, mappedBy = "crmActivity", fetch = FetchType.LAZY, targetEntity = CrmActivityCoupon.class)
	public List<CrmActivityCoupon> getCrmActivityCoupons() {
		if (crmActivityCoupons == null) {
			crmActivityCoupons = Lists.newArrayList();
		}
		return crmActivityCoupons;
	}

	public void setCrmActivityCoupons(List<CrmActivityCoupon> crmActivityCoupons) {
		this.crmActivityCoupons = crmActivityCoupons;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, targetEntity = CrmActivitySteps.class, mappedBy = "crmActivity", orphanRemoval = false)
	public List<CrmActivitySteps> getCrmActivitySteps() {
		if (crmActivitySteps == null) {
			crmActivitySteps = Lists.newArrayList();
		}
		return crmActivitySteps;
	}
	private List<CrmActivityVipScripts> crmActivityVipScripts;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, targetEntity = CrmActivityVipScripts.class, mappedBy = "crmActivity", orphanRemoval = false)
	public List<CrmActivityVipScripts> getCrmActivityVipScripts() {
		if (crmActivityVipScripts == null) {
			crmActivityVipScripts = Lists.newArrayList();
		}
		return crmActivityVipScripts;
	}
	public void setCrmActivityVipScripts(List<CrmActivityVipScripts> crmActivityVipScripts) {
		this.crmActivityVipScripts = crmActivityVipScripts;
	}


	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@SequenceGenerator(name = "seq", sequenceName = "CRM_ACTIVITY_S", allocationSize = 1)
	@Column(name = "CA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@Override
	public BigDecimal getId() {
		return this.caId;
	}



	/**
	 * 树叶节点默认图标 如果没有默认 空即可
	 *
	 * @return
	 */
	@Transient
	@Override
	public String getLeafDefaultIcon() {
		return "ztree_file";
	}






	@Column(name = "REMARK", length = 500)
	public String getRemark() {
		return this.remark;
	}




	

	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}




	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	@Column(name = "UPDATE_DT", length = 30)
	public String getUpdateDt() {
		return this.updateDt;
	}






	@Override
	public String makeSelfAsNewParentIds() {
		return getParentIds() + getId() + getSeparator();
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public void setCreateDt(String createDt) {
		this.createDt = createDt;
	}

	public void setCrmActivityActivitysManagers(List<CrmActivityActivitysManager> crmActivityActivitysManagers) {
		this.crmActivityActivitysManagers = crmActivityActivitysManagers;
	}

	public void setCrmActivityAds(List<CrmActivityAd> crmActivityAds) {
		this.crmActivityAds = crmActivityAds;
	}

	public void setCrmActivityHpoints(List<CrmActivityHpoint> crmActivityHpoints) {
		this.crmActivityHpoints = crmActivityHpoints;
	}

	public void setCrmActivityPromotions(List<CrmActivityPromotion> crmActivityPromotions) {
		this.crmActivityPromotions = crmActivityPromotions;
	}

	public void setCrmActivitySteps(List<CrmActivitySteps> crmActivitySteps) {
		this.crmActivitySteps = crmActivitySteps;
	}

	
	////////////////////////////////////////////////////////////////////////


	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}



	@Override
	public void setId(BigDecimal caId) {
		this.caId = caId;
	}



	public void setRemark(String remark) {
		this.remark = remark;
	}


	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public void setUpdateDt(String updateDt) {
		this.updateDt = updateDt;
	}
	
	@Transient
	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return getTitle();
	}
	@Transient
	@Override
	public String getDiy() {
		// TODO Auto-generated method stub
		return getId()+"";
	}

}
