package com.daphne.es.crm.activities.entity;
// Generated 2015-9-15 17:04:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import com.daphne.es.common.entity.AbstractEntity;

/**
 * CrmActivityVipScripts generated by hbm2java
 */
@Entity
@Table(name = "CRM_ACTIVITY_VIP_SCRIPTS", schema = "MAS")
public class CrmActivityVipScripts extends AbstractEntity<BigDecimal> {

	private BigDecimal cavsId;

	// private BigDecimal casId;
	//private BigDecimal caId;
	private String scripts;
	private BigDecimal controlRate;

	/////////////////////////////////////////////////////////////////////////////////

	private CrmActivitySteps crmActivitySteps;

	// private BigDecimal ;

	////////////////////////////////////////////////////////////////////////////////////

	public CrmActivityVipScripts(String scripts, BigDecimal controlRate) {
		super();
		this.scripts = scripts;
		this.controlRate = controlRate;

	}

	public CrmActivityVipScripts() {
		super();
	}

	@Column(name = "CONTROL_RATE", precision = 22, scale = 0)
	public BigDecimal getControlRate() {
		return this.controlRate;
	}

	private CrmActivity crmActivity;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CA_ID", insertable = true, updatable = true)
	public CrmActivity getCrmActivity() {
		return crmActivity;
	}

	public void setCrmActivity(CrmActivity crmActivity) {
		this.crmActivity = crmActivity;
	}

	@OneToOne(optional = false)
	@JoinColumn(name = "CAS_ID", referencedColumnName = "CAS_ID") //// 在CrmActivitySteps中，添加一个外键
	public CrmActivitySteps getCrmActivitySteps() {
		return crmActivitySteps;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@SequenceGenerator(name = "seq", sequenceName = "CRM_ACTIVITY_VIP_SCRIPTS_S", allocationSize = 1)
	@Column(name = "CAVS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@Override
	public BigDecimal getId() {
		return this.cavsId;
	}

	@Column(name = "SCRIPTS", length = 2500)
	public String getScripts() {
		return this.scripts;
	}

	public void setControlRate(BigDecimal controlRate) {
		this.controlRate = controlRate;
	}

//	@Column(name = "CA_ID", nullable = false, precision = 22, scale = 0)
//	public BigDecimal getCaId() {
//		return this.caId;
//	}
//
//	public void setCaId(BigDecimal caId) {
//		this.caId = caId;
//	}

	public void setCrmActivitySteps(CrmActivitySteps crmActivitySteps) {
		this.crmActivitySteps = crmActivitySteps;
	}

	@Override
	public void setId(BigDecimal cavsId) {
		this.cavsId = cavsId;
	}

	public void setScripts(String scripts) {
		this.scripts = scripts;
	}

	public void add(CrmActivityVipScripts crmActivityVipScripts) {
		// TODO Auto-generated method stub

	}

}
