package com.daphne.es.crm.activities.entity;
// Generated 2015-9-15 17:04:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.daphne.es.common.entity.AbstractEntity;

/**
 * CrmActivityVip generated by hbm2java
 */
@Entity
@Table(name = "CRM_ACTIVITY_VIP", schema = "MAS")
public class CrmActivityVip extends AbstractEntity<BigDecimal> {

	private BigDecimal cavId;
	private BigDecimal casId;
	private BigDecimal caId;
	private BigDecimal vip;
	private BigDecimal flag;
	private Date createDate;

	public CrmActivityVip() {
	}

	public CrmActivityVip(BigDecimal cavId, BigDecimal casId, BigDecimal caId) {
		this.cavId = cavId;
		this.casId = casId;
		this.caId = caId;
	}

	public CrmActivityVip(BigDecimal cavId, BigDecimal casId, BigDecimal caId, BigDecimal vip, BigDecimal flag,
			Date createDate) {
		this.cavId = cavId;
		this.casId = casId;
		this.caId = caId;
		this.vip = vip;
		this.flag = flag;
		this.createDate = createDate;
	}

	@Column(name = "CA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCaId() {
		return this.caId;
	}

	@Column(name = "CAS_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCasId() {
		return this.casId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	@Column(name = "FLAG", precision = 22, scale = 0)
	public BigDecimal getFlag() {
		return this.flag;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@SequenceGenerator(name = "seq", sequenceName = "CRM_ACTIVITY_VIP_S", allocationSize = 1)
	@Column(name = "CAV_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@Override
	public BigDecimal getId() {
		return this.cavId;
	}

	@Column(name = "VIP", precision = 22, scale = 0)
	public BigDecimal getVip() {
		return this.vip;
	}

	public void setCaId(BigDecimal caId) {
		this.caId = caId;
	}

	public void setCasId(BigDecimal casId) {
		this.casId = casId;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public void setFlag(BigDecimal flag) {
		this.flag = flag;
	}

	@Override
	public void setId(BigDecimal cavId) {
		this.cavId = cavId;
	}

	public void setVip(BigDecimal vip) {
		this.vip = vip;
	}

}
